//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Сontract_table = new HashSet<Сontract_table>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string passport_Num { get; set; }
        public string passport_Seria { get; set; }
        public int type { get; set; }
        public Nullable<int> legal_entity { get; set; }
        public string email { get; set; }
    
        public virtual Legal_entity Legal_entity1 { get; set; }
        public virtual Type_Cl Type_Cl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сontract_table> Сontract_table { get; set; }
    }
}
