//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Con_point
    {
        public int id { get; set; }
        public Nullable<int> adress { get; set; }
    
        public virtual Adress Adress1 { get; set; }
    }
}
