//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Other
    {
        public int id { get; set; }
        public int contract { get; set; }
        public int tariff { get; set; }
        public int type { get; set; }
    
        public virtual Service_Other_Type Service_Other_Type { get; set; }
        public virtual Сontract_table Сontract_table { get; set; }
        public virtual Tariff Tariff1 { get; set; }
    }
}
