//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_TV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service_TV()
        {
            this.Tv_Service_bundle = new HashSet<Tv_Service_bundle>();
        }
    
        public int id { get; set; }
        public int contract { get; set; }
        public int tariff { get; set; }
    
        public virtual Сontract_table Сontract_table { get; set; }
        public virtual Tariff Tariff1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tv_Service_bundle> Tv_Service_bundle { get; set; }
    }
}
