//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tv_Service_bundle
    {
        public int id { get; set; }
        public int service { get; set; }
        public int bundle { get; set; }
    
        public virtual Service_TV Service_TV { get; set; }
        public virtual Tv_bundle Tv_bundle { get; set; }
    }
}
