//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Client_Services
    {
        public string Клиент { get; set; }
        public int Номер_договора { get; set; }
        public Nullable<int> Номер_Net { get; set; }
        public Nullable<int> Номер_других_услуг { get; set; }
        public Nullable<int> Номер_TV { get; set; }
    }
}
