//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_legal_entities
    {
        public string Организация { get; set; }
        public string Представитель { get; set; }
        public string БИК { get; set; }
        public string Номер_Счета { get; set; }
        public int Номер_договора { get; set; }
        public Nullable<System.DateTime> Дата_подписания { get; set; }
        public Nullable<System.DateTime> Дата_окнчания { get; set; }
    }
}
