//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сontract_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сontract_table()
        {
            this.Service_Net = new HashSet<Service_Net>();
            this.Service_Other = new HashSet<Service_Other>();
            this.Service_TV = new HashSet<Service_TV>();
        }
    
        public int id { get; set; }
        public Nullable<int> client { get; set; }
        public Nullable<System.DateTime> Date_Begin { get; set; }
        public Nullable<System.DateTime> Date_End { get; set; }
    
        public virtual Client Client1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Net> Service_Net { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Other> Service_Other { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_TV> Service_TV { get; set; }
    }
}
